table _Measures
	lineageTag: e48cb90a-c7e7-475a-979b-895f83aabbcc

	measure Curr_temp_C = SUM('Current'[current.temp_c])&" °C"
		lineageTag: bbd22fb5-3159-41c1-9f24-92db8c3002c9

	column Column
		formatString: 0
		lineageTag: f5ab71e5-faab-41c4-abcd-1abce8e9cd57
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition _Measures = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 1043ec6514274ec6b45b51a0952780e9

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

