table Current
	lineageTag: bcf5adad-9fc2-4b09-af81-16d6cd31813c

	column 'location.name'
		dataType: string
		lineageTag: 2db419ac-adde-43f8-8396-8e02214ea021
		summarizeBy: none
		sourceColumn: location.name

		annotation SummarizationSetBy = Automatic

	column 'location.region'
		dataType: string
		lineageTag: 7232e3d3-d418-422a-b3e6-0b02e4cb000f
		summarizeBy: none
		sourceColumn: location.region

		annotation SummarizationSetBy = Automatic

	column 'location.country'
		dataType: string
		lineageTag: 2a69c119-d647-4b80-9f08-0d0553a81974
		summarizeBy: none
		sourceColumn: location.country

		annotation SummarizationSetBy = Automatic

	column 'location.lat'
		dataType: double
		lineageTag: 9721ea13-2d18-4b79-9074-bb38941e5ad8
		summarizeBy: sum
		sourceColumn: location.lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'location.lon'
		dataType: double
		lineageTag: 3fc5ba3b-1215-4809-85b6-f28067a83ea4
		summarizeBy: sum
		sourceColumn: location.lon

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'location.tz_id'
		dataType: string
		lineageTag: a622b975-0e87-431c-832f-3c245d932fad
		summarizeBy: none
		sourceColumn: location.tz_id

		annotation SummarizationSetBy = Automatic

	column 'location.localtime_epoch'
		dataType: int64
		formatString: 0
		lineageTag: 48318db5-ddb8-44a5-a9da-b3e37dbbc59a
		summarizeBy: sum
		sourceColumn: location.localtime_epoch

		annotation SummarizationSetBy = Automatic

	column 'location.localtime'
		dataType: dateTime
		formatString: General Date
		lineageTag: 45e6fd83-534f-44f2-8500-a3a3f86240bb
		summarizeBy: none
		sourceColumn: location.localtime

		variation Variation
			isDefault
			relationship: 871ed3f1-2475-4af1-ad9b-d4fbfe8b688b
			defaultHierarchy: LocalDateTable_43a81f47-3295-40ca-ae41-340e1e7e5b6c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'current.last_updated_epoch'
		dataType: int64
		formatString: 0
		lineageTag: 2aacf7dc-8245-40c6-880c-0c79eca8ae09
		summarizeBy: sum
		sourceColumn: current.last_updated_epoch

		annotation SummarizationSetBy = Automatic

	column 'current.last_updated'
		dataType: dateTime
		formatString: General Date
		lineageTag: 2aa3f110-014f-43ae-9fd7-552231db2f16
		summarizeBy: none
		sourceColumn: current.last_updated

		variation Variation
			isDefault
			relationship: 7959fc95-0fad-4690-a63e-c5c6fb1b31b0
			defaultHierarchy: LocalDateTable_3061b615-3cb9-4c5c-a2ee-99fe5f132893.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'current.temp_c'
		dataType: double
		lineageTag: b4cf1aea-1d3a-40ce-8b5b-5e838dbe6e89
		summarizeBy: sum
		sourceColumn: current.temp_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.temp_f'
		dataType: double
		lineageTag: 7d1c9814-575c-445f-b343-7a8e4402d510
		summarizeBy: sum
		sourceColumn: current.temp_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.is_day'
		dataType: int64
		formatString: 0
		lineageTag: 078578b3-53fb-41cf-a028-34476af67efd
		summarizeBy: sum
		sourceColumn: current.is_day

		annotation SummarizationSetBy = Automatic

	column 'current.condition.text'
		dataType: string
		lineageTag: 231677b0-54c8-478a-8191-6e830a26ef6b
		summarizeBy: none
		sourceColumn: current.condition.text

		annotation SummarizationSetBy = Automatic

	column 'current.condition.icon'
		dataType: string
		lineageTag: ac0607e1-d977-4ba6-82e5-c1428b5bae1c
		summarizeBy: none
		sourceColumn: current.condition.icon

		annotation SummarizationSetBy = Automatic

	column 'current.condition.code'
		dataType: int64
		formatString: 0
		lineageTag: 491c79ad-eeba-47a7-bf59-78f5bb3de830
		summarizeBy: sum
		sourceColumn: current.condition.code

		annotation SummarizationSetBy = Automatic

	column 'current.wind_mph'
		dataType: double
		lineageTag: 02871ade-6e9e-4b8f-89a4-81de26e6fc1e
		summarizeBy: sum
		sourceColumn: current.wind_mph

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.wind_kph'
		dataType: double
		lineageTag: ec6a6c78-1f03-49cb-a0d6-1f2dd0ce5558
		summarizeBy: sum
		sourceColumn: current.wind_kph

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.wind_degree'
		dataType: int64
		formatString: 0
		lineageTag: 06f49d5e-37da-48e4-86fb-842442c794c2
		summarizeBy: sum
		sourceColumn: current.wind_degree

		annotation SummarizationSetBy = Automatic

	column 'current.wind_dir'
		dataType: string
		lineageTag: 4a4254c4-cf6a-4b79-9a72-96476eec24f1
		summarizeBy: none
		sourceColumn: current.wind_dir

		annotation SummarizationSetBy = Automatic

	column 'current.pressure_mb'
		dataType: int64
		formatString: 0
		lineageTag: b65ba44e-e3be-48a9-ac6a-6591dcc86773
		summarizeBy: sum
		sourceColumn: current.pressure_mb

		annotation SummarizationSetBy = Automatic

	column 'current.pressure_in'
		dataType: double
		lineageTag: 8633218b-cf28-42ad-9ea4-d2f2947fd338
		summarizeBy: sum
		sourceColumn: current.pressure_in

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.precip_mm'
		dataType: int64
		formatString: 0
		lineageTag: 6ff0d585-c932-4a1b-bfd5-3d9b05b01d3a
		summarizeBy: sum
		sourceColumn: current.precip_mm

		annotation SummarizationSetBy = Automatic

	column 'current.precip_in'
		dataType: int64
		formatString: 0
		lineageTag: 777d1607-9080-4005-858e-4f49053ba58d
		summarizeBy: sum
		sourceColumn: current.precip_in

		annotation SummarizationSetBy = Automatic

	column 'current.humidity'
		dataType: int64
		formatString: 0
		lineageTag: f19066e4-73ac-4e01-8607-305d7cb6f13e
		summarizeBy: sum
		sourceColumn: current.humidity

		annotation SummarizationSetBy = Automatic

	column 'current.cloud'
		dataType: int64
		formatString: 0
		lineageTag: 6b193084-3a8e-4100-b073-93a778ee44ea
		summarizeBy: sum
		sourceColumn: current.cloud

		annotation SummarizationSetBy = Automatic

	column 'current.feelslike_c'
		dataType: double
		lineageTag: a9ba7b1d-3bb7-4994-9ae5-586e2810bc29
		summarizeBy: sum
		sourceColumn: current.feelslike_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.feelslike_f'
		dataType: double
		lineageTag: b05ed31f-d6c0-4897-8355-3cafad891a27
		summarizeBy: sum
		sourceColumn: current.feelslike_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.windchill_c'
		dataType: int64
		formatString: 0
		lineageTag: e6f92886-535c-485e-81c8-3668c570fdc8
		summarizeBy: sum
		sourceColumn: current.windchill_c

		annotation SummarizationSetBy = Automatic

	column 'current.windchill_f'
		dataType: double
		lineageTag: 0d171c0f-469a-43be-8eab-450df684ea35
		summarizeBy: sum
		sourceColumn: current.windchill_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.heatindex_c'
		dataType: int64
		formatString: 0
		lineageTag: fe972940-77d8-4291-bbc7-723d79815279
		summarizeBy: sum
		sourceColumn: current.heatindex_c

		annotation SummarizationSetBy = Automatic

	column 'current.heatindex_f'
		dataType: double
		lineageTag: 19b78f3a-c379-41bc-8393-b5748693da88
		summarizeBy: sum
		sourceColumn: current.heatindex_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.dewpoint_c'
		dataType: double
		lineageTag: 8c6c5ee2-bcd7-4d32-91fd-2493af3be9a2
		summarizeBy: sum
		sourceColumn: current.dewpoint_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.dewpoint_f'
		dataType: double
		lineageTag: 4f09a7ce-988e-4479-96fb-b2d0bd12e98d
		summarizeBy: sum
		sourceColumn: current.dewpoint_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.vis_km'
		dataType: int64
		formatString: 0
		lineageTag: e78bf205-7212-4929-85d9-714b16f17993
		summarizeBy: sum
		sourceColumn: current.vis_km

		annotation SummarizationSetBy = Automatic

	column 'current.vis_miles'
		dataType: int64
		formatString: 0
		lineageTag: e992945c-4979-4c12-a5a3-66a940f9b6bd
		summarizeBy: sum
		sourceColumn: current.vis_miles

		annotation SummarizationSetBy = Automatic

	column 'current.uv'
		dataType: double
		lineageTag: 1e1fda99-9a9d-48e5-870f-143012a1bc6d
		summarizeBy: sum
		sourceColumn: current.uv

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.gust_mph'
		dataType: double
		lineageTag: 6ab14887-cac2-44e0-b784-2aaafc8d47c9
		summarizeBy: sum
		sourceColumn: current.gust_mph

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.gust_kph'
		dataType: double
		lineageTag: 06aee0f3-084c-43e4-a65a-38baba5d49df
		summarizeBy: sum
		sourceColumn: current.gust_kph

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.air_quality.co'
		dataType: double
		lineageTag: 4843ce45-9c15-4cbb-9abf-039638ad5042
		summarizeBy: sum
		sourceColumn: current.air_quality.co

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.air_quality.no2'
		dataType: double
		lineageTag: 30a3a7fe-c049-474d-a325-c6dfddaa8d73
		summarizeBy: sum
		sourceColumn: current.air_quality.no2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.air_quality.o3'
		dataType: int64
		formatString: 0
		lineageTag: 9bca08e1-7b2b-4030-9efc-c836474483e9
		summarizeBy: sum
		sourceColumn: current.air_quality.o3

		annotation SummarizationSetBy = Automatic

	column 'current.air_quality.so2'
		dataType: double
		lineageTag: 837f0088-ff3d-4ff1-bb2a-4dbf4cb379f1
		summarizeBy: sum
		sourceColumn: current.air_quality.so2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.air_quality.pm2_5'
		dataType: double
		lineageTag: 4b530687-8d4b-4f33-9b8f-4a8c3417daab
		summarizeBy: sum
		sourceColumn: current.air_quality.pm2_5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.air_quality.pm10'
		dataType: double
		formatString: 0
		lineageTag: 2714d0a0-cd71-4d49-85f1-f1bf8c11c257
		summarizeBy: sum
		sourceColumn: current.air_quality.pm10

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'current.air_quality.us-epa-index'
		dataType: int64
		formatString: 0
		lineageTag: 7b749bae-e44b-4727-946c-ad8c842e4be8
		summarizeBy: sum
		sourceColumn: current.air_quality.us-epa-index

		annotation SummarizationSetBy = Automatic

	column 'current.air_quality.gb-defra-index'
		dataType: int64
		formatString: 0
		lineageTag: dfc32be4-b9a7-4060-9df9-89c1870d3589
		summarizeBy: sum
		sourceColumn: current.air_quality.gb-defra-index

		annotation SummarizationSetBy = Automatic

	column 'current.short_rad'
		dataType: double
		lineageTag: 3aada2ee-53e4-4561-befb-80eb4062dbfb
		summarizeBy: sum
		sourceColumn: current.short_rad

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.diff_rad'
		dataType: double
		lineageTag: 16eae20d-5d33-467b-9365-1c3a5620bc29
		summarizeBy: sum
		sourceColumn: current.diff_rad

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.dni'
		dataType: double
		lineageTag: 2f5119ce-78af-4c55-b6bc-ba02b9f323d3
		summarizeBy: sum
		sourceColumn: current.dni

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.gti'
		dataType: int64
		formatString: 0
		lineageTag: 4ca168f8-6a81-43fc-b2d7-6ca1a6f3c9ee
		summarizeBy: sum
		sourceColumn: current.gti

		annotation SummarizationSetBy = Automatic

	partition Current = m
		mode: import
		source =
				let
				    Source = MasterTable,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"forecast.forecastday.date", "forecast.forecastday.date_epoch", "forecast.forecastday.day.maxtemp_c", "forecast.forecastday.day.maxtemp_f", "forecast.forecastday.day.mintemp_c", "forecast.forecastday.day.mintemp_f", "forecast.forecastday.day.avgtemp_c", "forecast.forecastday.day.avgtemp_f", "forecast.forecastday.day.maxwind_mph", "forecast.forecastday.day.maxwind_kph", "forecast.forecastday.day.totalprecip_mm", "forecast.forecastday.day.totalprecip_in", "forecast.forecastday.day.totalsnow_cm", "forecast.forecastday.day.avgvis_km", "forecast.forecastday.day.avgvis_miles", "forecast.forecastday.day.avghumidity", "forecast.forecastday.day.daily_will_it_rain", "forecast.forecastday.day.daily_chance_of_rain", "forecast.forecastday.day.daily_will_it_snow", "forecast.forecastday.day.daily_chance_of_snow", "forecast.forecastday.day.condition.text", "forecast.forecastday.day.condition.icon", "forecast.forecastday.day.condition.code", "forecast.forecastday.day.uv", "forecast.forecastday.day.air_quality.co", "forecast.forecastday.day.air_quality.no2", "forecast.forecastday.day.air_quality.o3", "forecast.forecastday.day.air_quality.so2", "forecast.forecastday.day.air_quality.pm2_5", "forecast.forecastday.day.air_quality.pm10", "forecast.forecastday.day.air_quality.us-epa-index", "forecast.forecastday.day.air_quality.gb-defra-index", "forecast.forecastday.day.air_quality.aqi_data", "forecast.forecastday.astro.sunrise", "forecast.forecastday.astro.sunset", "forecast.forecastday.astro.moonrise", "forecast.forecastday.astro.moonset", "forecast.forecastday.astro.moon_phase", "forecast.forecastday.astro.moon_illumination", "forecast.forecastday.astro.is_moon_up", "forecast.forecastday.astro.is_sun_up", "forecast.forecastday.hour.time_epoch", "forecast.forecastday.hour.time", "forecast.forecastday.hour.temp_c", "forecast.forecastday.hour.temp_f", "forecast.forecastday.hour.is_day", "forecast.forecastday.hour.condition.text", "forecast.forecastday.hour.condition.icon", "forecast.forecastday.hour.condition.code", "forecast.forecastday.hour.wind_mph", "forecast.forecastday.hour.wind_kph", "forecast.forecastday.hour.wind_degree", "forecast.forecastday.hour.wind_dir", "forecast.forecastday.hour.pressure_mb", "forecast.forecastday.hour.pressure_in", "forecast.forecastday.hour.precip_mm", "forecast.forecastday.hour.precip_in", "forecast.forecastday.hour.snow_cm", "forecast.forecastday.hour.humidity", "forecast.forecastday.hour.cloud", "forecast.forecastday.hour.feelslike_c", "forecast.forecastday.hour.feelslike_f", "forecast.forecastday.hour.windchill_c", "forecast.forecastday.hour.windchill_f", "forecast.forecastday.hour.heatindex_c", "forecast.forecastday.hour.heatindex_f", "forecast.forecastday.hour.dewpoint_c", "forecast.forecastday.hour.dewpoint_f", "forecast.forecastday.hour.will_it_rain", "forecast.forecastday.hour.chance_of_rain", "forecast.forecastday.hour.will_it_snow", "forecast.forecastday.hour.chance_of_snow", "forecast.forecastday.hour.vis_km", "forecast.forecastday.hour.vis_miles", "forecast.forecastday.hour.gust_mph", "forecast.forecastday.hour.gust_kph", "forecast.forecastday.hour.uv", "forecast.forecastday.hour.air_quality.co", "forecast.forecastday.hour.air_quality.no2", "forecast.forecastday.hour.air_quality.o3", "forecast.forecastday.hour.air_quality.so2", "forecast.forecastday.hour.air_quality.pm2_5", "forecast.forecastday.hour.air_quality.pm10", "forecast.forecastday.hour.air_quality.us-epa-index", "forecast.forecastday.hour.air_quality.gb-defra-index", "forecast.forecastday.hour.short_rad", "forecast.forecastday.hour.diff_rad", "forecast.forecastday.hour.dni", "forecast.forecastday.hour.gti"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns"),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Duplicates","//","https://",Replacer.ReplaceText,{"current.condition.icon"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

