table Forecast_by_hour
	lineageTag: 68251560-9e32-404a-97be-f598cd9a1df8

	column 'location.name'
		dataType: string
		lineageTag: fe68b0ce-b713-43a9-b3ac-a53f6dab863d
		summarizeBy: none
		sourceColumn: location.name

		annotation SummarizationSetBy = Automatic

	column 'location.region'
		dataType: string
		lineageTag: 2b1626ed-8590-4fa3-a2fe-3e898a808f7e
		summarizeBy: none
		sourceColumn: location.region

		annotation SummarizationSetBy = Automatic

	column 'location.country'
		dataType: string
		lineageTag: 3b1270f0-d20e-4272-8ed1-1759bbe805d7
		summarizeBy: none
		sourceColumn: location.country

		annotation SummarizationSetBy = Automatic

	column 'location.lat'
		dataType: double
		lineageTag: b4fce1e5-d709-4be2-82c2-ba7ac9b67b21
		summarizeBy: sum
		sourceColumn: location.lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'location.lon'
		dataType: double
		lineageTag: 77130226-96bf-4a36-a260-6fa673f60b72
		summarizeBy: sum
		sourceColumn: location.lon

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'location.tz_id'
		dataType: string
		lineageTag: 31c547e9-15b2-414f-920b-92cc8cb76e88
		summarizeBy: none
		sourceColumn: location.tz_id

		annotation SummarizationSetBy = Automatic

	column 'location.localtime_epoch'
		dataType: int64
		formatString: 0
		lineageTag: fe5ba7b0-33a6-40bb-8f75-9e3dd39f82f8
		summarizeBy: sum
		sourceColumn: location.localtime_epoch

		annotation SummarizationSetBy = Automatic

	column 'location.localtime'
		dataType: dateTime
		formatString: General Date
		lineageTag: d081a736-86e4-4afc-8993-f24400acf38b
		summarizeBy: none
		sourceColumn: location.localtime

		variation Variation
			isDefault
			relationship: 8a837fdd-0d1c-47a0-a7e4-c4764c12299d
			defaultHierarchy: LocalDateTable_be6c64cd-86b7-4662-9bca-d8e8d7919720.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.time_epoch'
		dataType: int64
		formatString: 0
		lineageTag: 390204c0-4ec3-4f66-956c-dd3745f40f68
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.time_epoch

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.time'
		dataType: dateTime
		formatString: General Date
		lineageTag: e29c887f-76b8-46c2-bd0a-bbffe0e5fc5a
		summarizeBy: none
		sourceColumn: forecast.forecastday.hour.time

		variation Variation
			isDefault
			relationship: 72eb34fb-be96-4d23-b9a9-c133521eee00
			defaultHierarchy: LocalDateTable_27bae6c1-6141-4ad3-b008-c95a83ec62b8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.temp_c'
		dataType: double
		lineageTag: a4c976c1-c875-470d-b7d1-bd71deaf82a7
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.temp_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.temp_f'
		dataType: double
		lineageTag: 082c0bfd-bed8-45f4-9391-f3e5bcf438be
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.temp_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.is_day'
		dataType: int64
		formatString: 0
		lineageTag: 502f9bcb-4285-401e-a528-d3020c5a9197
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.is_day

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.condition.text'
		dataType: string
		lineageTag: b16ad114-9cf8-4612-a2dd-3b4082a2055d
		summarizeBy: none
		sourceColumn: forecast.forecastday.hour.condition.text

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.condition.icon'
		dataType: string
		lineageTag: 0b2a60b6-79f7-4a60-a78f-e91a54d5563d
		summarizeBy: none
		sourceColumn: forecast.forecastday.hour.condition.icon

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.condition.code'
		dataType: int64
		formatString: 0
		lineageTag: 8cc6fae0-f0c1-4708-82b3-e97e0c619e66
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.condition.code

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.wind_mph'
		dataType: double
		lineageTag: 1135409c-48f3-4691-b28e-e0e2987a01f7
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.wind_mph

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.wind_kph'
		dataType: double
		lineageTag: 2c5a8c53-4ab3-4d82-90f3-a3228f78628c
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.wind_kph

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.wind_degree'
		dataType: int64
		formatString: 0
		lineageTag: 51b8cdda-62ec-4c0e-a1ca-b471257a1422
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.wind_degree

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.wind_dir'
		dataType: string
		lineageTag: ff1dfc9b-2430-459e-b032-2c88b2b734e9
		summarizeBy: none
		sourceColumn: forecast.forecastday.hour.wind_dir

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.pressure_mb'
		dataType: int64
		formatString: 0
		lineageTag: c545c8ec-fa32-4546-9135-2d7542bc4ae1
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.pressure_mb

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.pressure_in'
		dataType: double
		lineageTag: ec6b317c-79fc-4539-96f7-c8cfeffff115
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.pressure_in

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.precip_mm'
		dataType: double
		lineageTag: ef2d7b9b-c208-4992-abad-f2f24f131091
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.precip_mm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.precip_in'
		dataType: int64
		formatString: 0
		lineageTag: 0f78d862-d616-4c2f-88f4-460845ab92ed
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.precip_in

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.snow_cm'
		dataType: int64
		formatString: 0
		lineageTag: 50760f52-57a8-4bb4-a5ee-e17bc105a44e
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.snow_cm

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.humidity'
		dataType: int64
		formatString: 0
		lineageTag: fd5c8b94-af90-48b7-9a5c-1cd0f727a71e
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.humidity

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.cloud'
		dataType: int64
		formatString: 0
		lineageTag: 31ead4e7-b783-4f65-8e01-71d6b42f5356
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.cloud

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.feelslike_c'
		dataType: double
		lineageTag: c237b5d8-3119-4dc9-bb87-2b92daed77e1
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.feelslike_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.feelslike_f'
		dataType: double
		lineageTag: 0e1c3e90-ff77-4e3a-b395-55ea6a09936a
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.feelslike_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.windchill_c'
		dataType: double
		lineageTag: 1e60da71-a51c-4efc-9d23-af6e7ad9b08d
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.windchill_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.windchill_f'
		dataType: double
		lineageTag: 2ab466a3-bece-4f49-8eb5-5bd0e82d5e4f
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.windchill_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.heatindex_c'
		dataType: double
		lineageTag: 0b8ad4b7-d7d2-4035-8c1f-8f8b84619043
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.heatindex_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.heatindex_f'
		dataType: double
		lineageTag: 778a453f-5691-4b91-8cae-1f2665dfb714
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.heatindex_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.dewpoint_c'
		dataType: double
		lineageTag: 60fa7bbc-e783-4e5d-bee1-49a0cfa12136
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.dewpoint_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.dewpoint_f'
		dataType: double
		lineageTag: 6ed7b880-e770-4a0d-b3e6-7ffa02849aa6
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.dewpoint_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.will_it_rain'
		dataType: int64
		formatString: 0
		lineageTag: b83ad1aa-03f0-40cd-9241-5abf4b81b0e6
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.will_it_rain

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.chance_of_rain'
		dataType: int64
		formatString: 0
		lineageTag: 6c5c8723-9c41-4b7e-b8f2-245155564e50
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.chance_of_rain

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.will_it_snow'
		dataType: int64
		formatString: 0
		lineageTag: dbc4bc39-eb72-442a-8963-d54b17c4d3f9
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.will_it_snow

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.chance_of_snow'
		dataType: int64
		formatString: 0
		lineageTag: c5d73bbf-0d8c-4c50-b9f6-0098a940e80c
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.chance_of_snow

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.vis_km'
		dataType: int64
		formatString: 0
		lineageTag: 976cffe4-22ba-4337-aa05-26f1ad6a9302
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.vis_km

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.vis_miles'
		dataType: int64
		formatString: 0
		lineageTag: 6cb56c7f-b964-43dc-b764-135cca42a184
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.vis_miles

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.gust_mph'
		dataType: double
		lineageTag: ecbcab62-3664-4871-a0c2-b8d8a2728501
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.gust_mph

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.gust_kph'
		dataType: double
		lineageTag: 2d9c0cde-0a3f-4db2-bf08-c7fe0970ab52
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.gust_kph

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.uv'
		dataType: double
		lineageTag: 19243b96-a1e6-4c3f-af71-eb630fca31ef
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.uv

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.air_quality.co'
		dataType: double
		lineageTag: dae7a126-2d42-43fe-b8d3-4fab634b1a45
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.air_quality.co

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.air_quality.no2'
		dataType: double
		lineageTag: bdef09d4-69e5-4a6a-b570-4160005677bc
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.air_quality.no2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.air_quality.o3'
		dataType: int64
		formatString: 0
		lineageTag: 8031c88c-91fa-4648-8369-010af90380a4
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.air_quality.o3

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.air_quality.so2'
		dataType: double
		lineageTag: 4305ac50-03f2-45fc-be03-9db00cd9dc16
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.air_quality.so2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.air_quality.pm2_5'
		dataType: double
		lineageTag: eff44b64-21b1-47ce-92d5-f04fc12d3591
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.air_quality.pm2_5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.air_quality.pm10'
		dataType: double
		lineageTag: 643724db-c181-4a8a-a1db-fc3c2f43ec31
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.air_quality.pm10

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.air_quality.us-epa-index'
		dataType: int64
		formatString: 0
		lineageTag: b5b7f32e-bb07-4f47-a723-4e14ca5cb4c3
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.air_quality.us-epa-index

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.air_quality.gb-defra-index'
		dataType: int64
		formatString: 0
		lineageTag: ce2a612d-deb3-483a-a8ac-392906a3bc9d
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.air_quality.gb-defra-index

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.short_rad'
		dataType: double
		lineageTag: cf5733c9-b823-4f13-89e4-2f5c3389dfb4
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.short_rad

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.diff_rad'
		dataType: double
		lineageTag: 2e436e76-4efd-4702-a96d-552f38f6b3bd
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.diff_rad

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.dni'
		dataType: double
		lineageTag: 73831381-285b-41e7-bad9-3da243a6412b
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.dni

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.gti'
		dataType: double
		lineageTag: 15009cb8-44f3-418d-aa54-2c4325cbb39e
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.gti

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Forecast_by_hour = m
		mode: import
		source =
				let
				    Source = MasterTable,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"current.last_updated_epoch", "current.last_updated", "current.temp_c", "current.temp_f", "current.is_day", "current.condition.text", "current.condition.icon", "current.condition.code", "current.wind_mph", "current.wind_kph", "current.wind_degree", "current.wind_dir", "current.pressure_mb", "current.pressure_in", "current.precip_mm", "current.precip_in", "current.humidity", "current.cloud", "current.feelslike_c", "current.feelslike_f", "current.windchill_c", "current.windchill_f", "current.heatindex_c", "current.heatindex_f", "current.dewpoint_c", "current.dewpoint_f", "current.vis_km", "current.vis_miles", "current.uv", "current.gust_mph", "current.gust_kph", "current.air_quality.co", "current.air_quality.no2", "current.air_quality.o3", "current.air_quality.so2", "current.air_quality.pm2_5", "current.air_quality.pm10", "current.air_quality.us-epa-index", "current.air_quality.gb-defra-index", "current.short_rad", "current.diff_rad", "current.dni", "current.gti", "forecast.forecastday.date", "forecast.forecastday.date_epoch", "forecast.forecastday.day.maxtemp_c", "forecast.forecastday.day.maxtemp_f", "forecast.forecastday.day.mintemp_c", "forecast.forecastday.day.mintemp_f", "forecast.forecastday.day.avgtemp_c", "forecast.forecastday.day.avgtemp_f", "forecast.forecastday.day.maxwind_mph", "forecast.forecastday.day.maxwind_kph", "forecast.forecastday.day.totalprecip_mm", "forecast.forecastday.day.totalprecip_in", "forecast.forecastday.day.totalsnow_cm", "forecast.forecastday.day.avgvis_km", "forecast.forecastday.day.avgvis_miles", "forecast.forecastday.day.avghumidity", "forecast.forecastday.day.daily_will_it_rain", "forecast.forecastday.day.daily_chance_of_rain", "forecast.forecastday.day.daily_will_it_snow", "forecast.forecastday.day.daily_chance_of_snow", "forecast.forecastday.day.condition.text", "forecast.forecastday.day.condition.icon", "forecast.forecastday.day.condition.code", "forecast.forecastday.day.uv", "forecast.forecastday.day.air_quality.co", "forecast.forecastday.day.air_quality.no2", "forecast.forecastday.day.air_quality.o3", "forecast.forecastday.day.air_quality.so2", "forecast.forecastday.day.air_quality.pm2_5", "forecast.forecastday.day.air_quality.pm10", "forecast.forecastday.day.air_quality.us-epa-index", "forecast.forecastday.day.air_quality.gb-defra-index", "forecast.forecastday.day.air_quality.aqi_data", "forecast.forecastday.astro.sunrise", "forecast.forecastday.astro.sunset", "forecast.forecastday.astro.moonrise", "forecast.forecastday.astro.moonset", "forecast.forecastday.astro.moon_phase", "forecast.forecastday.astro.moon_illumination", "forecast.forecastday.astro.is_moon_up", "forecast.forecastday.astro.is_sun_up"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns","//","https://",Replacer.ReplaceText,{"forecast.forecastday.hour.condition.icon"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

