table Forecast_by_day
	lineageTag: 45f22232-4b79-4ff6-976b-56073fdb5462

	column 'location.name'
		dataType: string
		lineageTag: 15b6895b-7aa4-40fb-b8c3-6979fa41b421
		summarizeBy: none
		sourceColumn: location.name

		annotation SummarizationSetBy = Automatic

	column 'location.region'
		dataType: string
		lineageTag: 6b7a948b-d4f5-4c14-b535-e61b70f15021
		summarizeBy: none
		sourceColumn: location.region

		annotation SummarizationSetBy = Automatic

	column 'location.country'
		dataType: string
		lineageTag: bc2076f5-1b7f-4f29-a5d2-b7116485a539
		summarizeBy: none
		sourceColumn: location.country

		annotation SummarizationSetBy = Automatic

	column 'location.lat'
		dataType: double
		lineageTag: df842967-c292-4822-830a-bfe5299df96e
		summarizeBy: sum
		sourceColumn: location.lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'location.lon'
		dataType: double
		lineageTag: fca8e0a8-8966-4962-99ff-be19d863f6e6
		summarizeBy: sum
		sourceColumn: location.lon

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'location.tz_id'
		dataType: string
		lineageTag: b82b418e-d717-48c4-9423-2a88a22a2a2d
		summarizeBy: none
		sourceColumn: location.tz_id

		annotation SummarizationSetBy = Automatic

	column 'location.localtime_epoch'
		dataType: int64
		formatString: 0
		lineageTag: 2315d15f-f9ff-4484-a68d-4098fc313812
		summarizeBy: sum
		sourceColumn: location.localtime_epoch

		annotation SummarizationSetBy = Automatic

	column 'location.localtime'
		dataType: dateTime
		formatString: General Date
		lineageTag: 43722078-f29d-48cb-bb9c-1035bbaf5461
		summarizeBy: none
		sourceColumn: location.localtime

		variation Variation
			isDefault
			relationship: fdf4c5eb-65d4-4a22-8f34-5a559ae45cf3
			defaultHierarchy: LocalDateTable_de9ea630-cb8d-475d-b8ed-9648ab3e453c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 782dece4-aae5-46ab-b398-c31bf3e9318e
		summarizeBy: none
		sourceColumn: forecast.forecastday.date

		variation Variation
			isDefault
			relationship: bef2f6c5-fc77-45d1-aaff-0a5af5709ffd
			defaultHierarchy: LocalDateTable_dac05772-9f4e-4aee-a581-ca11060bdf4b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'forecast.forecastday.date_epoch'
		dataType: int64
		formatString: 0
		lineageTag: b730bbca-3eac-4947-886d-cff50c4e86ce
		summarizeBy: sum
		sourceColumn: forecast.forecastday.date_epoch

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.maxtemp_c'
		dataType: double
		lineageTag: 49c7c8ee-5c31-4f29-a284-6eb179bca462
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.maxtemp_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.maxtemp_f'
		dataType: double
		lineageTag: d4c9db31-c6d3-4839-b250-c1b5c624c7d2
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.maxtemp_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.mintemp_c'
		dataType: double
		lineageTag: b593600d-11ed-43f2-941e-ea38b2cb76ef
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.mintemp_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.mintemp_f'
		dataType: double
		lineageTag: b6747ca6-1b6c-4dda-998a-c052411ad955
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.mintemp_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.avgtemp_c'
		dataType: double
		lineageTag: dd0fdb22-f139-4fe5-8df2-77b077793ad9
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.avgtemp_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.avgtemp_f'
		dataType: double
		lineageTag: 8e4b63e2-2881-4f83-9e3e-3ceca825045d
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.avgtemp_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.maxwind_mph'
		dataType: double
		lineageTag: d7271660-5935-45c9-a7d4-7d2a2eec9ce8
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.maxwind_mph

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.maxwind_kph'
		dataType: double
		lineageTag: a9886106-f03f-429c-80ad-3d6ad6494f53
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.maxwind_kph

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.totalprecip_mm'
		dataType: double
		lineageTag: da526749-159e-4f76-9e36-cf82a5d2c076
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.totalprecip_mm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.totalprecip_in'
		dataType: double
		lineageTag: 55b320e2-5cd9-4d59-ac49-a30851d3905b
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.totalprecip_in

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.totalsnow_cm'
		dataType: int64
		formatString: 0
		lineageTag: 25c359b3-c4cd-439c-8642-59b3b453fbe1
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.totalsnow_cm

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.avgvis_km'
		dataType: int64
		formatString: 0
		lineageTag: 1feafb89-8911-4d27-ac3b-6cab2087d909
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.avgvis_km

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.avgvis_miles'
		dataType: int64
		formatString: 0
		lineageTag: 85429192-81db-464e-bf24-16355f3155bf
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.avgvis_miles

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.avghumidity'
		dataType: int64
		formatString: 0
		lineageTag: 4df5711b-6493-4810-bb5c-fb5343d299aa
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.avghumidity

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.daily_will_it_rain'
		dataType: int64
		formatString: 0
		lineageTag: fb3ffc45-4c0b-41dc-954c-d6cf650dbbfc
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.daily_will_it_rain

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.daily_chance_of_rain'
		dataType: int64
		formatString: 0
		lineageTag: 5ed4294c-4630-4403-a796-79ca84be932b
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.daily_chance_of_rain

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.daily_will_it_snow'
		dataType: int64
		formatString: 0
		lineageTag: 49f813cb-4860-4231-8bc7-619254d36010
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.daily_will_it_snow

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.daily_chance_of_snow'
		dataType: int64
		formatString: 0
		lineageTag: 7c7e816c-e1ab-4e72-aa10-d16aceb786b8
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.daily_chance_of_snow

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.condition.text'
		dataType: string
		lineageTag: c064f361-76ae-477f-9b1a-38938e1cc1c8
		summarizeBy: none
		sourceColumn: forecast.forecastday.day.condition.text

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.condition.icon'
		dataType: string
		lineageTag: ebd9d117-d2ed-4f34-bd01-b70fe1ee7c7c
		summarizeBy: none
		sourceColumn: forecast.forecastday.day.condition.icon

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.condition.code'
		dataType: int64
		formatString: 0
		lineageTag: 21f74f2f-b47a-4440-9bcd-401854dd8e82
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.condition.code

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.uv'
		dataType: double
		lineageTag: 860218d9-0d4e-496a-970a-946e71deb60f
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.uv

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.air_quality.co'
		dataType: double
		lineageTag: 80f186c8-ae4b-49a7-9be3-ce00bf3ded01
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.air_quality.co

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.air_quality.no2'
		dataType: double
		lineageTag: 01b09b0c-6363-4c43-872c-5061c3e813e6
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.air_quality.no2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.air_quality.o3'
		dataType: double
		lineageTag: 1c009cc6-7303-40eb-819d-617050734b1d
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.air_quality.o3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.air_quality.so2'
		dataType: double
		lineageTag: f929c29b-0568-4b3c-b92d-2dc453e9f796
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.air_quality.so2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.air_quality.pm2_5'
		dataType: double
		lineageTag: 07f1afa8-0ded-4e52-8a72-d56f14a6fe23
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.air_quality.pm2_5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.air_quality.pm10'
		dataType: double
		lineageTag: 712cce16-c93c-40ab-bcea-ce63d7126740
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.air_quality.pm10

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.air_quality.us-epa-index'
		dataType: int64
		formatString: 0
		lineageTag: 895af59a-46cf-4283-9568-53d52e7a5525
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.air_quality.us-epa-index

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.air_quality.gb-defra-index'
		dataType: int64
		formatString: 0
		lineageTag: e694cee9-187a-4c8d-884b-c4a822f80894
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.air_quality.gb-defra-index

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.air_quality.aqi_data'
		dataType: string
		lineageTag: ea6401c7-b4af-4b93-a51b-05350254d2c0
		summarizeBy: none
		sourceColumn: forecast.forecastday.day.air_quality.aqi_data

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.astro.sunrise'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 71b8fa89-5885-4373-a0bc-922a771df451
		summarizeBy: none
		sourceColumn: forecast.forecastday.astro.sunrise

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'forecast.forecastday.astro.sunset'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 60a01380-744f-47d8-9a1c-d352b98ceb9d
		summarizeBy: none
		sourceColumn: forecast.forecastday.astro.sunset

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'forecast.forecastday.astro.moonrise'
		dataType: dateTime
		formatString: Long Time
		lineageTag: a0b56420-6f0b-4c79-beb9-0e5eb7110dc4
		summarizeBy: none
		sourceColumn: forecast.forecastday.astro.moonrise

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'forecast.forecastday.astro.moonset'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 39307bb2-34ba-4b08-a354-171c7c7270d9
		summarizeBy: none
		sourceColumn: forecast.forecastday.astro.moonset

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'forecast.forecastday.astro.moon_phase'
		dataType: string
		lineageTag: 7f4fbf21-e8cc-47f0-9afc-ebc48e827bce
		summarizeBy: none
		sourceColumn: forecast.forecastday.astro.moon_phase

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.astro.moon_illumination'
		dataType: int64
		formatString: 0
		lineageTag: 7323bc74-9764-410d-be3e-121125bbaa0b
		summarizeBy: sum
		sourceColumn: forecast.forecastday.astro.moon_illumination

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.astro.is_moon_up'
		dataType: int64
		formatString: 0
		lineageTag: 26560845-347f-4621-af3b-e67d08cdd5b3
		summarizeBy: sum
		sourceColumn: forecast.forecastday.astro.is_moon_up

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.astro.is_sun_up'
		dataType: int64
		formatString: 0
		lineageTag: 5e71830d-3d85-4fef-a2f8-4ec7b2cf0316
		summarizeBy: sum
		sourceColumn: forecast.forecastday.astro.is_sun_up

		annotation SummarizationSetBy = Automatic

	column Day_Name = Format(Forecast_by_day[forecast.forecastday.date], "ddd")
		lineageTag: 24baf972-a95f-442f-9e9d-63b3db65343a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Forecast_by_day = m
		mode: import
		source =
				let
				    Source = MasterTable,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"current.last_updated_epoch", "current.last_updated", "current.temp_c", "current.temp_f", "current.is_day", "current.condition.text", "current.condition.icon", "current.condition.code", "current.wind_mph", "current.wind_kph", "current.wind_degree", "current.wind_dir", "current.pressure_mb", "current.pressure_in", "current.precip_mm", "current.precip_in", "current.humidity", "current.cloud", "current.feelslike_c", "current.feelslike_f", "current.windchill_c", "current.windchill_f", "current.heatindex_c", "current.heatindex_f", "current.dewpoint_c", "current.dewpoint_f", "current.vis_km", "current.vis_miles", "current.uv", "current.gust_mph", "current.gust_kph", "current.air_quality.co", "current.air_quality.no2", "current.air_quality.o3", "current.air_quality.so2", "current.air_quality.pm2_5", "current.air_quality.pm10", "current.air_quality.us-epa-index", "current.air_quality.gb-defra-index", "current.short_rad", "current.diff_rad", "current.dni", "current.gti", "forecast.forecastday.hour.time_epoch", "forecast.forecastday.hour.time", "forecast.forecastday.hour.temp_c", "forecast.forecastday.hour.temp_f", "forecast.forecastday.hour.is_day", "forecast.forecastday.hour.condition.text", "forecast.forecastday.hour.condition.icon", "forecast.forecastday.hour.condition.code", "forecast.forecastday.hour.wind_mph", "forecast.forecastday.hour.wind_kph", "forecast.forecastday.hour.wind_degree", "forecast.forecastday.hour.wind_dir", "forecast.forecastday.hour.pressure_mb", "forecast.forecastday.hour.pressure_in", "forecast.forecastday.hour.precip_mm", "forecast.forecastday.hour.precip_in", "forecast.forecastday.hour.snow_cm", "forecast.forecastday.hour.humidity", "forecast.forecastday.hour.cloud", "forecast.forecastday.hour.feelslike_c", "forecast.forecastday.hour.feelslike_f", "forecast.forecastday.hour.windchill_c", "forecast.forecastday.hour.windchill_f", "forecast.forecastday.hour.heatindex_c", "forecast.forecastday.hour.heatindex_f", "forecast.forecastday.hour.dewpoint_c", "forecast.forecastday.hour.dewpoint_f", "forecast.forecastday.hour.will_it_rain", "forecast.forecastday.hour.chance_of_rain", "forecast.forecastday.hour.will_it_snow", "forecast.forecastday.hour.chance_of_snow", "forecast.forecastday.hour.vis_km", "forecast.forecastday.hour.vis_miles", "forecast.forecastday.hour.gust_mph", "forecast.forecastday.hour.gust_kph", "forecast.forecastday.hour.uv", "forecast.forecastday.hour.air_quality.co", "forecast.forecastday.hour.air_quality.no2", "forecast.forecastday.hour.air_quality.o3", "forecast.forecastday.hour.air_quality.so2", "forecast.forecastday.hour.air_quality.pm2_5", "forecast.forecastday.hour.air_quality.pm10", "forecast.forecastday.hour.air_quality.us-epa-index", "forecast.forecastday.hour.air_quality.gb-defra-index", "forecast.forecastday.hour.short_rad", "forecast.forecastday.hour.diff_rad", "forecast.forecastday.hour.dni", "forecast.forecastday.hour.gti"}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Removed Columns", {{"forecast.forecastday.astro.moonset", null}}),
				    #"Removed Duplicates" = Table.Distinct(#"Replaced Errors"),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Duplicates","//","https://",Replacer.ReplaceText,{"forecast.forecastday.day.condition.icon"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

